### ISSUE TITLE
master doesn't work on python 3.7 and 3.6

### ISSUE THREAD

**Issue by tomaszmrugalski** [gut-space/satnogs#39]
The recent change in backend/app/repository.py imports TypedDict from typing. Unfortunately, on python 3.7.5 it does fails:
```
File "/home/thomson/devel/satnogs/backend/app/repository.py", line 9, in <module>
    from typing import Any, Dict, List, TypedDict, NewType, Sequence, NoReturn, Union, Optional, Tuple
ImportError: cannot import name 'TypedDict' from 'typing' (/usr/lib/python3.7/typing.py)
```

See https://docs.python.org/3.7/library/typing.html and https://docs.python.org/3.8/library/typing.html

**Comment by fivitti** [comment]
TypedDict (and Literal) is a part of Python from 3.8 version.

Previously it was a part of ~~[MyPy extensions](https://pypi.org/project/mypy-extensions/)~~ [typing_extensions](https://pypi.org/project/typing-extensions/). We can import TypedDict from this package when we recognize that Python version is less then 3.8.

We need to analyze which versions of Python we want to support. The content server uses Python 3.8, but Raspberry Pi uses 3.7 (latest version in stable Debian repo).

**Comment by fivitti** [comment]
MyPy documentation recommend using [typing_extensions](https://pypi.org/project/typing-extensions/) for TypedDict and Literal.

**Comment by fivitti** [comment]
```python
if sys.version_info[0] == 3 and sys.version_info[1] >= 8:
    from typing import TypedDict, Literal
else:
    from typing_extensions import TypedDict, Literal
```

**Comment by tomaszmrugalski** [comment]
I think it's time to fix the travis CI tests and start paying attention to their status. It would have been picked by travis (builds on python 3.6, 3.7 and 3.8), but we didn't have the postgres setup completed there. I try to fix that.

**Comment by tomaszmrugalski** [comment]
This has been fixed with #40 merge.

**Comment by Sushang-Agnihotri** [comment]
Try to Uninstall the related librarie(s) and install it again. 
it worked for me.
